### ISSUE TITLE
Create a data resource for querying Hardware Reservations

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#241]
The [Hardware Resevations](https://www.packet.com/developers/docs/getting-started/deployment-options/reserved-hardware/) [API](https://www.packet.com/developers/api/hardwarereservations/) should be represented as a Data resource.

This will enable more flexibility when defining [hardware_reservation_id in the packet_device](https://www.terraform.io/docs/providers/packet/r/device.html#hardware_reservation_id).

https://github.com/packethost/packngo/blob/cc9e9b7/hardware_reservations.go#L42-L68

**Comment by t0mk** [comment]
@displague, will this offer anything over `wait_for_reservation_deprovision`?

https://www.terraform.io/docs/providers/packet/r/device.html#wait_for_reservation_deprovision
https://github.com/terraform-providers/terraform-provider-packet/blob/master/packet/resource_packet_device.go#L578

If yes, would you like to do it yourself, or would you like me to the datasource?

**Comment by displague** [comment]
I wasn't aware of [wait_for_reservation_deprovision](https://www.terraform.io/docs/providers/packet/r/device.html#wait_for_reservation_deprovision).

Does this allow for a reserved hardware device to be reprovisioned (through the terraform lifecycle) on the same device? That would seem to settle: https://github.com/terraform-providers/terraform-provider-packet/issues/236#issuecomment-662759535 (which is where the urge to pursue this data resource came from).

**Comment by t0mk** [comment]
@displague I am not sure if  wait_for_reservation_deprovision allows to reprovision on the same device.

It can only be used with hw res ID together. If you set the w_f_r_d attr, `terraform delete` will then block until the reservation is marked provisionable again.

IIUC, there is only one device in a hw reservation. If you (terraform) destroy a device resource with hw res id with thew w_f_r_d attr set, and then run `terraform apply` on the same template, the device should be re-deployed on the same device (same hw res).

I will take a look on the linked issue.

**Comment by t0mk** [comment]
I don't see how their problem (#236) would be resolved with hw res.

**Comment by displague** [comment]
This has been implemented in the Equinix Metal provider. Closing this.

https://github.com/equinix/terraform-provider-metal/issues/86

_This will not be implemented in the legacy Packet provider_.
