### ISSUE TITLE
add a data resource for getting ssh keys

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#249]
There is currently no way to query and access an existing Packet Project SSH Keys through Terraform.

Create a data resource for project ssh keys.

**Comment by displague** [comment]
https://github.com/packethost/packngo/pull/190 would enable a three-field `search` parameter for this data resource.
The existing `SSHKeyServiceOp.ProjectList` in packngo is sufficient for this data source.

**Comment by t0mk** [comment]
@displague I'll take a look during the weekend or on Monday

**Comment by gianarb** [comment]
Not sure about why this one is assigned to me :)

**Comment by displague** [comment]
This resource was included in the Packet provider and is present in the Equinix Metal provider.
