### ISSUE TITLE
Advanced example of packet_device_network_type

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#252]
We've seen a few questions in slack wondering about how to use `packet_device_network_type` in more advanced scenarios.

https://github.com/tinkerbell/tink/pull/276/files#r482165856 is indicative of the kinds of questions we are seeing.

Provide an example that:

- reflects different network types (hybrid, layer2, etc)
- reflects vlan_port_attachments (and a depends_on, if needed)
- reflects multiple devices, network_types, and vlan_port_attachments (count >1)

**Comment by displague** [comment]
@dsieczko should be tagged for review when ready.

**Comment by t0mk** [comment]
@displague 
There are some more advanced examples in 
https://registry.terraform.io/providers/packethost/packet/latest/docs/resources/port_vlan_attachment#example-usage

notes
* It could be linked from the packet_device_network_type doc.
* There's a formatting error, not dividing the two examples.
* The 2 devices scenario could be added.

**Comment by displague** [comment]
That sounds good @t0mk. I'd like to see a `count = 2` or similar on the device because it isn't obvious that the `depends_on` has to refer to the named resource (not the matching indexed device, due to TF limitations).
