### ISSUE TITLE
Update docs/ to the new TF registry format

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#259]
The updated docs format for Terraform Registry standards is defined at https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs. 

The erb index is no longer needed, the directory structure changes, the files can use simpler ".md" filenames, and "guides/" are now supported.

**Comment by t0mk** [comment]
@displague will you do this, or should I take care of it? I have one improvement for packet_project doc that I'd like to get in, but maybe I will wait till the docs are converted to the new format.

**Comment by displague** [comment]
@t0mk Take all the issues you want 😅 !

https://github.com/packethost/terraform-provider-packet/issues/252 would be good to pick up if you want to improve some docs while reformatting.

Also docs related, but not needed for this, one of the new recommendations (https://github.com/packethost/terraform-provider-packet/issues/258) is that each Schema field should include "Description: " (which can be markdown) in addition to the `.md` file contents.  I would assume that we will have generators in the future to produce the `md` files from the go code. I think the Terraform language server in VS Code can benefit from this to provide field descriptions when editing HCL.

**Comment by displague** [comment]
I made a similar set of TF13 docs changes in another provider: https://github.com/equinix/terraform-provider-equinix/pull/11/commits/44f6335ffc268274b940825559aa255ac6f2b006

**Comment by t0mk** [comment]
@displague OK, I will do the doc migration then. I will wait until #250 is merged.

**Comment by displague** [comment]
I've noted this in TF12+ readied providers:

```Makefile
website:
	@echo "Use this site to preview markdown rendering: https://registry.terraform.io/tools/doc-preview"
```

**Comment by t0mk** [comment]
@displague thanks for the tip!

**Comment by t0mk** [comment]
@displague that's only to check how markdown will render, it doesn't help to verify whether all the necessary files are at the right place and nothing's missing.

**Comment by displague** [comment]
I found out about https://github.com/bflad/tfproviderdocs today.
