### ISSUE TITLE
Test sweeper may fail to delete provisioning devices

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#266]
During a test run with failures, the test sweeper regularly fails to delete devices that are still provisioning.

I'd like for the sweeper to deal with these things immediately. It is debatable that this is exactly the type of problem that we have a scheduled test and sweep job phase for. It will eventually resolve.  It should leave at most one test build of resources behind.

```
2020/10/01 20:19:14 [ERR] error running (packet_organization): Error deleting device DELETE https://api.packet.net/devices/25fb6701-a45e-40c9-8ace-bc0af69b6855: 422 Cannot delete a device while it is provisioning 
FAIL	github.com/packethost/terraform-provider-packet/packet	12.970s
FAIL
Error: Process completed with exit code 1.
```

Is this a problem? Can we (or should we bother) putting a time gap in to allow for provisions to settle before running the sweeper?

Do we need to prevent multiple build jobs from running so that the sweeper doesn't attempt to run while a second build (with provisioning devices) is active?

_Originally posted by @displague in https://github.com/packethost/terraform-provider-packet/pull/261#issuecomment-702514245_

**Comment by t0mk** [comment]
@displague yes I think it's a problem if sweeper doesn't sweep, and I can't see any other solution that polling wait for "active" state.

**Comment by displague** [comment]
This was addressed in https://github.com/equinix/terraform-provider-metal/issues/25
