### ISSUE TITLE
packet_device_network_type not able to handle manual device removal

### ISSUE THREAD

**Issue by invidian** [packethost/terraform-provider-packet#267]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
$ /usr/bin/terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/packethost/packet v3.0.1
+ provider registry.terraform.io/poseidon/ct v0.6.1
+ provider registry.terraform.io/tinkerbell/tinkerbell v0.1.0

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_device_network_type
- packet_port_vlan_attachment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "packet_device" "worker" {
  project_id       = var.project_id
  facilities       = [var.facility]
  hostname         = var.name
  plan             = var.device_type
  operating_system = "custom_ipxe"
  ipxe_script_url  = "https://boot.netboot.xyz"
  always_pxe       = "true"
  billing_cycle    = "hourly"
}

resource "packet_device_network_type" "worker" {
  device_id = packet_device.worker.id
  type      = "layer2-individual"
}

```

### Expected Behavior
`packet_device_network_type` read function should  just set resource ID to `""` to schedule it for re-creation when when device is no longer present.

### Actual Behavior
Terraform returns following error:
```
Error: GET https://api.packet.net/devices/de3ba0e4-3d14-4093-ab0f-f38cb8c73644?include=facility: 404 Not found
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Remove created device via Packet portal
3. `terraform apply`

### Workaround

To workaround that, affected `packet_device_network_type` can be removed manually from state using `terraform state rm` command.

**Comment by invidian** [comment]
Ah, it seems this also affects `packet_port_vlan_attachment` resource.

**Comment by displague** [comment]
Similarly, if during the port attachment unbinding (delete) we encounter a 404, the unbind could be considered successful.

**Comment by displague** [comment]
https://github.com/packethost/terraform-provider-packet/pull/268 seeks to correct this, please have a look @invidian - and thanks for pointing this out!

**Comment by displague** [comment]
Closing this issue as #268 may have solved it here, while the broader handling of device 403 and 404 responses while modifying ports. 

The Equinix Metal provider (https://github.com/equinix/terraform-provider-metal) has corrected this and is the successor to this Packet provider, which is being deprecated.

**Comment by invidian** [comment]
Sorry for lack of feedback regarding if this has been resolved, but I didn't find time for it, so I trust you it's better now :+1:
