### ISSUE TITLE
Add deprovision speed improvement booleans

### ISSUE THREAD

**Issue by kyledrake** [packethost/terraform-provider-packet#77]
https://www.packet.com/developers/changelog/deprovision-speed-improvements/

**Comment by t0mk** [comment]
@kyledrake After some research, (and as silly as it sounds) I am not sure if rebooting/reinstalling a server is possible with Terraform. It doesn't have the notion of the actions, only state transitions, and the `reinstalled` state is very hard to define.

I looked at couple of other providers and there are no actions on compute resources. Would you have an example how it's done elsewhere? Have you been using TF for reinstalling?

We have a Packet CLI in pipeline, and this would be a perfect fit.

I will add the flags to packngo (the golang API lib), and illustrate with acceptance tests.

**Comment by t0mk** [comment]
If you really want to do a reinstall via Terraform, you can wrap a curl command in local-exec in a null_resource, like this:

```
resource "null_resource" "issue_reinstall" {

  provisioner "local-exec" {
    on_failure  = "fail"
    interpreter = ["/bin/bash", "-c"]
    command     = <<EOT
        echo -e "\x1B[31m Reinstalling device ${packet_device.test.id}\x1B[0m"
        curl -v -H "X-Auth-Token: $PACKET_AUTH_TOKEN" -H 'Content-Type: application/json' "https://api.packet.net/devices/${packet_device.test.id}/actions" -d '{"type":"reinstall"}'
        echo "************** Reinstalling *********************"
    EOT
  }

  triggers = {
    always_run = "${timestamp()}"
  }
}
```

**Comment by mrmrcoleman** [comment]
Hey @kyledrake does @t0mk 's suggestion above solve your issue, or do you have further requirements for this issue?

**Comment by invidian** [comment]
See also how OVH Terraform provider deals with reboots via Terraform: https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/dedicated_server_reboot_task

**Comment by t0mk** [comment]
@invidian thanks, that's news for me. I will take a look of we could do sth like that here.

**Comment by displague** [comment]
Closing this issue as this provider is being deprecated in favor of the Equinix Metal provider 
https://github.com/equinix/terraform-provider-metal

This is an interesting problem that we want to revisit there.
